import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Navbar from "./Navbar";
import "./globals.css";

const vazir = Vazirmatn({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${vazir.className} bg-hero h-[100vh] bg-cover bg-no-repeat`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
